### PR TITLE
Fix RULE-22-3 test

### PR DESCRIPTION
**Pull request by mbaluda**
## Description

Fix compilation issue with test for RULE-22-3

## Change request type

 - [ ] Release or process automation (GitHub workflows, internal scripts)
 - [ ] Internal documentation
 - [ ] External documentation
 - [x] Query files (`.ql`, `.qll`, `.qls` or unit tests)
 - [ ] External scripts (analysis report or other code shipped as part of a release)

## Rules with added or modified queries

 - [x] No rules added
 - [ ] Queries have been added for the following rules:
     - _rule number here_
 - [ ] Queries have been modified for the following rules:
     - _rule number here_

## Release change checklist

A change note ([development_handbook.md#change-notes](https://github.com/github/codeql-coding-standards/blob/main/docs/development_handbook.md#change-notes)) is required for any pull request which modifies:

 - The structure or layout of the release artifacts.
 - The evaluation performance (memory, execution time) of an existing query.
 - The results of an existing query in any circumstance.

If you are only adding new rule queries, a change note is not required.

_**Author:**_ Is a change note required? 
  - [ ] Yes
  - [x] No

🚨🚨🚨
_**Reviewer:**_ Confirm that format of *shared* queries (not the .qll file, the
.ql file that imports it) is valid by running them within VS Code. 
  - [ ] Confirmed

_**Reviewer:**_ Confirm that either a change note is not required or the change note is required and has been added.
  - [ ] Confirmed

### CODE REVIEW

**Comment by jsinglet** [comment]
🤖 Beep Boop! **gcc/cpp/x86_64** Matrix Testing for this PR has been completed but I didn't find anything to test!

**Comment by jsinglet** [comment]
🤖 Beep Boop! **clang/cpp/x86_64** Matrix Testing for this PR has been completed but I didn't find anything to test!

**Comment by jsinglet** [comment]
🤖 Beep Boop! **clang/c/x86_64** Matrix Testing for this PR has been completed. See below for the results! <br><br>
``` 

COMPILE_ERROR_OUTPUT : 
TEST_DIFFERENCE      : 
PACKAGE              : IO3
TEST_PASS            : True
RULE                 : RULE-22-3
COMPILE_PASS         : True
SUITE                : MISRA-C-2012
QUERY                : FileOpenForReadAndWriteOnDifferentStreams


```

**Comment by jsinglet** [comment]
🤖 Beep Boop! **gcc/c/x86_64** Matrix Testing for this PR has been completed. See below for the results! <br><br>
``` 

PACKAGE              : IO3
COMPILE_ERROR_OUTPUT : 
TEST_DIFFERENCE      : 
SUITE                : MISRA-C-2012
QUERY                : FileOpenForReadAndWriteOnDifferentStreams
RULE                 : RULE-22-3
COMPILE_PASS         : True
TEST_PASS            : True


```

**Comment by jsinglet** [comment]
🤖 Beep Boop! Matrix Testing for this PR has been **completed**. If no reports were posted it means this PR does not contain things that need matrix testing!

**Comment by jsinglet** [comment]
🤖 Beep Boop! **clang/c/x86_64** Matrix Testing for this PR has been completed. See below for the results! <br><br>
``` 

QUERY                : FileOpenForReadAndWriteOnDifferentStreams
COMPILE_ERROR_OUTPUT : 
COMPILE_PASS         : True
RULE                 : RULE-22-3
PACKAGE              : IO3
TEST_PASS            : True
SUITE                : MISRA-C-2012
TEST_DIFFERENCE      : 


```

**Comment by jsinglet** [comment]
🤖 Beep Boop! **gcc/c/x86_64** Matrix Testing for this PR has been completed. See below for the results! <br><br>
``` 

COMPILE_PASS         : True
SUITE                : MISRA-C-2012
RULE                 : RULE-22-3
QUERY                : FileOpenForReadAndWriteOnDifferentStreams
COMPILE_ERROR_OUTPUT : 
TEST_PASS            : True
PACKAGE              : IO3
TEST_DIFFERENCE      : 


```

**Comment by jsinglet** [comment]
🤖 Beep Boop! Matrix Testing for this PR has been **completed**. If no reports were posted it means this PR does not contain things that need matrix testing!

**Review by lcartey — APPROVED** [review]

**Pull request merged**
