### PR TITLE
A0-1-1: Fix useless assignment false positive on constexpr array size

### PR DESCRIPTION
**Pull request by fjatWbyT**
## Description

Addresses false positive like the one in #690 in another AUTOSAR ule. 

## Change request type

 - [ ] Release or process automation (GitHub workflows, internal scripts)
 - [ ] Internal documentation
 - [ ] External documentation
 - [x] Query files (`.ql`, `.qll`, `.qls` or unit tests)
 - [ ] External scripts (analysis report or other code shipped as part of a release)

## Rules with added or modified queries

 - [ ] No rules added
 - [ ] Queries have been added for the following rules:
     - _rule number here_
 - [x] Queries have been modified for the following rules:
     - A0-1-1

## Release change checklist

A change note ([development_handbook.md#change-notes](https://github.com/github/codeql-coding-standards/blob/main/docs/development_handbook.md#change-notes)) is required for any pull request which modifies:

 - The structure or layout of the release artifacts.
 - The evaluation performance (memory, execution time) of an existing query.
 - The results of an existing query in any circumstance.

If you are only adding new rule queries, a change note is not required.

_**Author:**_ Is a change note required? 
  - [x] Yes
  - [ ] No

🚨🚨🚨
_**Reviewer:**_ Confirm that format of *shared* queries (not the .qll file, the
.ql file that imports it) is valid by running them within VS Code. 
  - [ ] Confirmed

_**Reviewer:**_ Confirm that either a change note is not required or the change note is required and has been added.
  - [ ] Confirmed

## Query development review checklist

For PRs that add new queries or modify existing queries, the following checklist should be completed by both the author and reviewer:

### Author

 - [x] Have all the relevant rule package description files been checked in?
 - [x] Have you verified that the metadata properties of each new query is set appropriately?
 - [ ] Do all the unit tests contain both "COMPLIANT" and "NON_COMPLIANT" cases?
 - [ ] Are the alert messages properly formatted and consistent with the [style guide](https://github.com/github/codeql-coding-standards/blob/main/docs/development_handbook.md#query-style-guide)?
 - [ ] Have you run the queries on OpenPilot and verified that the performance and results are acceptable?<br />_As a rule of thumb, predicates specific to the query should take no more than 1 minute, and for simple queries be under 10 seconds. If this is not the case, this should be highlighted and agreed in the code review process._
 - [x] Does the query have an appropriate level of in-query comments/documentation?
 - [x] Have you considered/identified possible edge cases?
 - [x] Does the query not reinvent features in the standard library?
 - [x] Can the query be simplified further (not golfed!)

### Reviewer 

 - [ ] Have all the relevant rule package description files been checked in?
 - [ ] Have you verified that the metadata properties of each new query is set appropriately?
 - [ ] Do all the unit tests contain both "COMPLIANT" and "NON_COMPLIANT" cases?
 - [ ] Are the alert messages properly formatted and consistent with the [style guide](https://github.com/github/codeql-coding-standards/blob/main/docs/development_handbook.md#query-style-guide)?
 - [ ] Have you run the queries on OpenPilot and verified that the performance and results are acceptable?<br />_As a rule of thumb, predicates specific to the query should take no more than 1 minute, and for simple queries be under 10 seconds. If this is not the case, this should be highlighted and agreed in the code review process._
 - [ ] Does the query have an appropriate level of in-query comments/documentation?
 - [ ] Have you considered/identified possible edge cases?
 - [ ] Does the query not reinvent features in the standard library?
 - [ ] Can the query be simplified further (not golfed!)

### CODE REVIEW

**Comment by fjatWbyT** [comment]
Hello @lcartey,

I looked for unit tests analogous to the one updated in #690, in this case for A0-1-1 "useless assignment", in contrast with M0-1-9 "no dead code", but couldn't find any already existing. I run locally the (153) tests in `cpp/common/test/rules` after applying the change and all pass. I could find tests for useless assignment in deviations, but I doubt those need updating for this change since there's no new deviation.

Does it make sense to add explicit coverage for A0-1-1?
I wonder if it would be sensible to (a) add a new directory `cpp/common/uselessassignment`, (b) update configuration so that the ones in `cpp/common/deadcode` are also run against A0-1-1, or (c) something else :)
On the one hand, I think that covering these other `isUselessSsaDefinition` predicate and `InterestingStackVariable` class (assuming they aren't already) would be an improvement. On the other hand, since they are (at least partially) used by the dead code qll, it might not be worth further updates.

**Comment by lcartey** [comment]
Hi @fjatWbyT! Thanks for the PR.

The test cases for `A0-1-1` live here:
https://github.com/github/codeql-coding-standards/tree/main/cpp/autosar/test/rules/A0-1-1

The tests live in a common directory when one query implementation is shared by multiple rules - for example, where an AUTOSAR and CERT C++ rule cover the same issue. `A0-1-1` is only required to be reported to AUTOSAR, so the tests live in the AUTOSAR test directory, under the rule ID.

**Comment by fjatWbyT** [comment]
Aaah, it is clear now. Thank you very much for the explanation. I will update the PR with extra coverage for this case in that file.

**Review by lcartey — APPROVED** [review]
Thank you!

**Pull request merged**
